# Generated by Django 3.2.4 on 2021-06-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskLister', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='taska',
        ),
    ]
