# Generated by Django 3.2.4 on 2021-06-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskLister', '0002_rename_todo_taska'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='taska',
        ),
    ]
