# Generated by Django 3.2.4 on 2021-07-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskLister', '0003_auto_20210612_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_text',
            new_name='task_title',
        ),
    ]
